language: node_js
sudo: required
node_js:
- '10.15'
branches:
  only:
  - master
  - stable
before_script:
- npm install
script:
- npm run build:linux
- npm run build:osx
- "./scripts/tar-linux.sh"
deploy:
  provider: releases
  api_key:
    secure: p/ezfa9DmSDtsYjFHCn76AhYPD+WbEgRnQjjI8uo2cP5P7/NesDLM5OSh9HRqkxG85htjyYLDrxzwfUazcca5XuHrHPfdE3HJ5wTCJEZees2G+bZIODtnbA3vEQmOBbXN9egZ4MGjY3cyBEIDL5w9qSYL/jvt52duzjSzFKQ44z5vQqYJDHrsqBp2Br8tjSSEFXU5w+s2omM7tl7hQqIG4+dsAna8Y7RMxCWnaH0yXqwyiPaA6+IijmoWecGzp6b1OeHPAa7q51jynP8HRNk8GJKI/i07qp/cCd70uDedRryvqCcXXcU56hA+kfGEV8h5Kgo6s0Tg8CFYi3UURlmznlPnNR1cve0QX+2DHHOE3vvvToMvpKq2R9cH5GgMkLFng/UcIcb34wi2szzqertSJrWM1AxVGEX27pVa4p1s8MCnqUfcpEnsrKj/qwAkLtKRZ0Tr3jbv+zRmw4ieL2/VZPzrerUIsjnHU4aPUwPAPQwxdfVZBCWJhi/DVzeEZrQczIoqkE8ZF5aEEA7m0L6Md7tMGSnoCCuaHV+PHJhTsEgPCYe82bbLWBbUwEB0MoVQw7OIhfiZiBDMbxO/v+Na/v/9EO0MhYNV91uwpao+ZcXyuy4MWyjIv4tKI/yxukUp2kUYVNVIz81XEcaZb1iVInenG0Xn9HWdzAGL8TIHh8=
  file:
  - 'dist/mac-osx.tar.gz'
  - 'dist/linux-x64.tar.xz'
  - 'dist/app-src.tgz'
  skip_cleanup: true
  on:
    repo: kjx98/electronic-wechat
    branch: stable
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d6bab2376f47ee992d78
    on_success: always
    on_failure: always
    on_start: always
